[Appearance]
icon_theme = Papirus-Dark
style = Fusion
color_scheme_path = /usr/share/qt6ct/colors/Oxocarbon.conf
standard_dialogs = default
[Fonts]
fixed = JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0
general = JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0
