# ==========================================================
# Xero Hypridle
# Smart Idle Management
# ==========================================================


general {

    # Lock screen
    lock_cmd = pidof hyprlock || hyprlock


    # Lock before suspend
    before_sleep_cmd = loginctl lock-session


    # Restore display after resume
    after_sleep_cmd = hyprctl dispatch dpms on
}



# ==========================================================
# Lock after inactivity
# ==========================================================

listener {

    # 10 minutes
    timeout = 600

    on-timeout = loginctl lock-session
}



# ==========================================================
# Turn display off
# ==========================================================

listener {

    # 12 minutes
    timeout = 720

    on-timeout = hyprctl dispatch dpms off

    on-resume = hyprctl dispatch dpms on
}



# ==========================================================
# Suspend (optional)
# ==========================================================

listener {

    # 30 minutes
    timeout = 1800

    on-timeout = systemctl suspend
}
