local home = os.getenv("HOME")

hl.on("hyprland.start", function()
	hl.dsp.exec_cmd("waybar")()
	hl.dsp.exec_cmd("swaync")()
	hl.dsp.exec_cmd("awww-daemon")()
	hl.dsp.exec_cmd(home .. "/.config/hypr/scripts/wallpaper.sh")()
	hl.dsp.exec_cmd("hypridle")()
	hl.dsp.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")()
	hl.dsp.exec_cmd("wl-paste --watch cliphist store")()
end)
