local home = os.getenv("HOME")

hl.on("hyprland.start", function()
	hl.dispatch(hl.dsp.exec_cmd("waybar"))
	hl.dispatch(hl.dsp.exec_cmd("swaync"))
	hl.dispatch(hl.dsp.exec_cmd("awww-daemon"))
	hl.dispatch(hl.dsp.exec_cmd(home .. "/.config/hypr/scripts/wallpaper.sh"))
	hl.dispatch(hl.dsp.exec_cmd("hypridle"))
	hl.dispatch(hl.dsp.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"))
	hl.dispatch(hl.dsp.exec_cmd("wl-paste --watch cliphist store"))
end)
